theme = "catppuccin_mocha"

[editor]
scrolloff = 15
mouse = false
line-number = "relative"
cursorline = true
bufferline = "always"
color-modes = true
text-width = 100
popup-border = "all"
end-of-line-diagnostics = "hint"
true-color = true
continue-comments = false

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "warning"

# ---------------------------------------- NORMAL MODE ----------------------------------------

[keys.normal]
# Disable keys
U = "no_op"
"C-w" = "no_op"
# Collapse
esc = ["collapse_selection", "keep_primary_selection"]
# Vim-like movements
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
# Vim-like operations
V = ["select_mode", "extend_to_line_bounds"]
x = "delete_selection"
p = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]
w = ["move_next_word_start", "move_char_right", "collapse_selection"]
W = ["move_next_long_word_start", "move_char_right", "collapse_selection"]
e = ["move_next_word_end", "collapse_selection"]
E = ["move_next_long_word_end", "collapse_selection"]
b = ["move_prev_word_start", "collapse_selection"]
B = ["move_prev_long_word_start", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]
u = ["undo", "collapse_selection"]
"C-r" = ["redo", "collapse_selection"]
# Find word under
"*" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "search_next",
]
"#" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "search_prev",
]
# Clone cursor
"A-j" = ["copy_selection_on_next_line"]
"A-k" = ["copy_selection_on_prev_line"]
# LSP Hover
K = "hover"
# Tab movement
tab = ["goto_next_buffer"]
S-tab = ["goto_previous_buffer"]
# Misc
H = ["move_prev_word_start", "collapse_selection"]
L = ["move_next_word_start", "collapse_selection"]

# Disable some goto keys
[keys.normal.g]
k = "no_op"
j = "no_op"
h = "no_op"
l = "no_op"
e = "no_op"
s = "no_op"
n = "no_op"
p = "no_op"
d = "no_op"
D = "no_op"
i = "no_op"
y = "no_op"
r = "no_op"

# Delete mode
[keys.normal.d]
d = [
  "extend_to_line_bounds",
  "yank_main_selection_to_clipboard",
  "delete_selection",
]
"$" = [
  "extend_to_line_end",
  "yank_main_selection_to_clipboard",
  "delete_selection",
]
"^" = [
  "extend_to_first_nonwhitespace",
  "yank_main_selection_to_clipboard",
  "delete_selection",
]
"0" = [
  "extend_to_line_start",
  "yank_main_selection_to_clipboard",
  "delete_selection",
]
G = [
  "select_mode",
  "extend_to_last_line",
  "extend_to_line_end",
  "yank_main_selection_to_clipboard",
  "delete_selection",
  "normal_mode",
]
g = { g = [
  "select_mode",
  "extend_to_file_start",
  "yank_main_selection_to_clipboard",
  "delete_selection",
  "normal_mode",
] }

# Yank
[keys.normal.y]
y = [
  "extend_to_line_bounds",
  "yank_main_selection_to_clipboard",
  "normal_mode",
  "collapse_selection",
]

# Leader
[keys.normal.space]
# Disable keys
a = "no_op"
c = "no_op"
C = "no_op"
D = "no_op"
F = "no_op"
G = "no_op"
h = "no_op"
j = "no_op"
k = "no_op"
p = "no_op"
P = "no_op"
r = "no_op"
R = "no_op"
s = "no_op"
S = "no_op"
y = "no_op"
Y = "no_op"
"A-c" = "no_op"
"?" = "no_op"
"'" = "no_op"
# Remap
e = "file_explorer_in_current_buffer_directory"
E = "file_explorer"
"/" = "toggle_comments"

# Find mode
[keys.normal.space.f]
b = "buffer_picker"
f = "file_picker"
F = "file_picker_in_current_directory"
r = "last_picker"
s = "global_search"
# s = "search" -- Just use /
w = [
  "move_prev_word_start",
  "select_mode",
  "move_next_word_end",
  "search_selection_detect_word_boundaries",
  "global_search",
]

# Buffer
[keys.normal.space.b]
c = ":buffer-close"
x = ":buffer-close"
o = ":buffer-close-others"
a = ":buffer-close-all"
n = ":buffer-next"
p = ":buffer-previous"

# Diagnostics
[keys.normal.space.d]
d = "diagnostics_picker"
w = "workspace_diagnostics_picker"

# LSP
[keys.normal.space.l]
a = "code_action"
f = ":format"
d = "goto_definition"
D = "goto_declaration"
i = "goto_implementation"
r = "goto_reference"
R = "rename_symbol"

# Windows
[keys.normal.space.w]
# split
n = "vsplit"
d = "hsplit"
c = "wclose"
x = "wclose"
# Disable keys
q = "no_op"
s = "no_op"
v = "no_op"
w = "no_op"
"up" = "no_op"
"down" = "no_op"
"left" = "no_op"
"right" = "no_op"
"C-q" = "no_op"
"C-o" = "no_op"
"C-w" = "no_op"
"C-h" = "no_op"
"C-j" = "no_op"
"C-k" = "no_op"
"C-l" = "no_op"
"C-s" = "no_op"
"C-v" = "no_op"
"C-t" = "no_op"

# ---------------------------------------- INSERT MODE ----------------------------------------

[keys.insert]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
tab = "insert_tab"
"C-h" = "delete_word_backward"

# ---------------------------------------- VISUAL MODE ----------------------------------------

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
0 = "extend_to_line_start"
"$" = "extend_to_line_end"
"^" = "extend_to_first_nonwhitespace"
G = "extend_to_file_end"
S = "surround_add"
u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]
i = "select_textobject_inner"
a = "select_textobject_around"
j = ["extend_line_down"]
"A-j" = ["copy_selection_on_next_line"]
k = ["extend_line_up"]
"A-k" = ["copy_selection_on_prev_line"]
d = ["yank_main_selection_to_clipboard", "delete_selection"]
x = ["delete_selection"]
y = ["yank_main_selection_to_clipboard", "collapse_selection"]
V = "extend_to_line_bounds"
tab = ["indent", "select_mode"]
S-tab = ["unindent", "select_mode"]

[keys.select.space]
# ## Disable keys
a = "no_op"
b = "no_op"
c = "no_op"
C = "no_op"
d = "no_op"
D = "no_op"
f = "no_op"
F = "no_op"
g = "no_op"
G = "no_op"
h = "no_op"
j = "no_op"
k = "no_op"
p = "no_op"
P = "no_op"
r = "no_op"
R = "no_op"
s = "no_op"
S = "no_op"
y = "no_op"
Y = "no_op"
w = "no_op"
"A-c" = "no_op"
"?" = "no_op"
"'" = "no_op"
# #Comment
# "/" = "toggle_line_comments"
"/" = "toggle_block_comments"
