[language-server.rust-analyzer.config]
check = { command = "clippy" }
cargo = { features = "all" }

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true
