[language-server.rust-analyzer.config]
check = { command = "clippy" }
cargo = { features = "all" }

[language-server.clangd]
command = "clangd"
args = [
  "--background-index",
  "--completion-style=bundled",
  "--header-insertion=iwyu",
  "--enable-config",
  "--malloc-trim",
  "--pch-storage=memory",
  "-j=8",
]

[[language]]
name = "cpp"
language-servers = ["clangd"]
roots = [".git", ".clangd", ".clang-format", "meson.build", "CMakeLists.txt"]
auto-format = true

[[language]]
name = "c"
language-servers = ["clangd"]
roots = [".git", ".clangd", ".clang-format", "meson.build", "CMakeLists.txt"]
auto-format = true

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true
