[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

[language-server.clangd]
command = "clangd"
args = ["--background-index", "-j=8", "--malloc-trim", "--pch-storage=memory"]
required-root-patterns = [".clangd", ".clang-format"]

[language-server.cmake-language-server]
command = "cmake-language-server"
args = ["start"]
required-root-patterns = ["CMakeLists.txt"]

[language-server.ruff]
command = "ruff"
args = ["server"]
required-root-patterns = ["ruff.toml", ".ruff.toml", "pyproject.toml"]

[language-server.taplo]
command = "taplo"
args = ["lsp", "stdio"]

##################### LANGUAGE #####################

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt" }
language-servers = ["bash-language-server"]

[[language]]
name = "c"
auto-format = true
language-servers = ["clangd"]
formatter = { command = "clang-format" }

[[language]]
name = "cpp"
auto-format = true
language-servers = ["clangd"]
formatter = { command = "clang-format" }

[[language]]
name = "cmake"
auto-format = false
language-servers = ["cmake-language-server"]

[[language]]
name = "fish"
auto-format = true
formatter = { command = "fish_indent" }

[[language]]
name = "python"
auto-format = true
language-servers = ["ruff"]

[[language]]
name = "toml"
auto-format = true
language-servers = ["taplo"]

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "yamlfmt", args = ["-in"] }
