[language-server.clangd]
command = "clangd"
args = ["--background-index", "-j=8", "--malloc-trim", "--pch-storage=memory"]
required-root-patterns = [".clangd"]

[[language]]
name = "cpp"
language-servers = ["clangd"]

[[language]]
name = "c"
language-servers = ["clangd"]

[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]

[[language]]
name = "python"
language-servers = ["ruff"]
