if command -v git &>/dev/null; then
	abbr -a gcl 'git clone'
	abbr -a gpl 'git pull --rebase'
	abbr -a grs 'git reset --hard HEAD^'
	abbr -a glo 'git log --oneline'
	abbr -a gst 'git status'
	abbr -a gdf 'git diff'
	abbr -a gad 'git add'
	abbr -a gau 'git add -u'
	abbr -a gco 'git checkout'
	abbr -a gcb 'git checkout -b'
	abbr -a gbr 'git branch'
	abbr -a gsh 'git stash'
	abbr -a gcm 'git commit'
	abbr -a gca 'git commit --amend'
fi
