abbr -a gco 'git checkout'
abbr -a gcm 'git commit'
abbr -a gca 'git commit --amend'
abbr -a gcn 'git commit --amend --no-edit'
abbr -a grs 'git clean -f -d && git reset --hard HEAD^^ && git pull --rebase'
abbr -a gpo 'git push origin'
abbr -a gpl 'git pull --rebase'
abbr -a gcl 'git clone'
abbr -a gst 'git status'
abbr -a gdf 'git diff'
abbr -a gad 'git add'
abbr -a glo 'git log --oneline'
abbr -a gpp 'git_push_now'
abbr -a gpy 'git_push_now --yolo'
