function! LoadCoreConfigs() abort
  let l:vimrc_dir = fnamemodify(expand('<sfile>'), ':p:h')
  let l:vim_core = l:vimrc_dir .. '/.vim/core/**/*.vim'
  let l:vim_plug = l:vimrc_dir .. '/.vim/plugin/**/*.vim'

  for l:f in glob(l:vim_core, 1, 1)
    execute 'source' l:f
  endfor

  for l:f in glob(l:vim_plug, 1, 1)
    execute 'source' l:f
  endfor

endfunction

call LoadCoreConfigs()
