# Mocha Color Palette
set -g red          f38ba8
set -g orange       fab387
set -g yellow       f9e2af
set -g green        a6e3a1
set -g cyan         94e2d5
set -g blue         89b4fa
set -g purple       f5c2e7
set -g pink         eba0ac
set -g white        cdd6f4
set -g gray         6c7086

set -l foreground   $white
set -l selection    $gray
set -l comment      $blue

set -g fish_color_normal            cdd6f4
set -g fish_color_command           89b4fa
set -g fish_color_param             f2cdcd
set -g fish_color_keyword           f38ba8
set -g fish_color_quote             a6e3a1
set -g fish_color_redirection       f5c2e7
set -g fish_color_end               fab387
set -g fish_color_comment           7f849c
set -g fish_color_error             f38ba8
set -g fish_color_gray              6c7086
set -g fish_color_option            a6e3a1
set -g fish_color_operator          f5c2e7
set -g fish_color_escape            eba0ac
set -g fish_color_autosuggestion    6c7086
set -g fish_color_cancel            f38ba8
set -g fish_color_cwd               f9e2af
set -g fish_color_user              94e2d5
set -g fish_color_host              89b4fa
set -g fish_color_host_remote       a6e3a1
set -g fish_color_status            f38ba8
set -g fish_pager_color_progress    6c7086
set -g fish_pager_color_prefix      f5c2e7
set -g fish_pager_color_completion  cdd6f4
set -g fish_pager_color_description 6c7086

set -g fish_color_selection --background=313244
set -g fish_color_search_match --background=313244
