fork = true
frame = "full"
idle = true
maximized = true
neovim-bin = "nvim"
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font]
normal = ["CodeNewRoman Nerd Font"]
size = 14.0
