fork = true
frame = "full"
idle = false
maximized = true
neovim-bin = "nvim"
no-multigrid = false
srgb = false
tabs = false
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font]
normal = ["CodeNewRoman Nerd Font Mono"]
size = 14.0
