return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  main = "nvim-treesitter.configs",
  opts = {
    ensure_installed = {
      "lua",
      "c",
      "cpp",
      "python",
      "javascript",
      "typescript",
      "vimdoc",
      "vim",
      "regex",
      "rust",
      "sql",
      "dockerfile",
      "toml",
      "json",
      "jsonc",
      "gitignore",
      "yaml",
      "make",
      "cmake",
      "markdown",
      "markdown_inline",
      "bash",
      "css",
      "scss",
      "html",
      "yuck",
      "hyprlang",
    },
    auto_install = true,
    highlight = {
      enable = true,
    },
    indent = {
      enable = true,
    },
  },
}
