import = [
    # "~/.config/alacritty/themes/catppuccin-latte.toml"
    # "~/.config/alacritty/themes/catppuccin-frappe.toml"
    # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 16.0
normal = { family = "CaskaydiaCove NFM", style = "Regular" }
bold = { family = "CaskaydiaCove NFM", style = "Bold" }
italic = { family = "CaskaydiaCove NFM", style = "Italic" }
bold_italic = { family = "CaskaydiaCove NFM", style = "Bold Italic"}

[keyboard]
bindings = [
    { key = "N",        mods = "Control|Shift", action = "SpawnNewInstance" },
    { key = "T",        mods = "Control|Shift", action = "CreateNewWindow"  },
    { key = "C",        mods = "Control|Shift", action = "Copy"             },
    { key = "V",        mods = "Control|Shift", action = "Paste"            },
    { key = "F",        mods = "Control|Shift", action = "SearchForward"    },
    { key = "B",        mods = "Control|Shift", action = "SearchBackward"   },
    { key = "U",        mods = "Control",       action = "ScrollPageUp"     },
    { key = "D",        mods = "Control",       action = "ScrollPageDown"   },
    { key = "Escape",   mods = "Control",       action = "ClearSelection"   },
]

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
decorations = "Full"
opacity = 0.9
blur = true
startup_mode = "Maximized"
dynamic_title = true
decorations_theme_variant = "Dark"
# option_as_alt = "OnlyLeft"
